# Generated by Django 4.0.1 on 2022-02-26 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='join_date',
            new_name='date_joined',
        ),
    ]
