# Generated by Django 4.0.1 on 2022-03-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='text', unique=True),
            preserve_default=False,
        ),
    ]
